use Teste_Analista_N2
CREATE TABLE TB_LOJA(
   ID_LOJA     INT IDENTITY (1,1) PRIMARY KEY
  ,ID_PARCEIRO INT FOREIGN KEY REFERENCES TB_PARCEIRO (ID_PARCEIRO)
  ,ID_CAMPANHA INT FOREIGN KEY REFERENCES TB_CAMPANHA (ID_CAMPANHA)
  ,NOME_LOJA   NVARCHAR(30)
  ,VIVISEL     BIT
  ,STATUS_LOJA NVARCHAR(30)
);