use Teste_Analista_N2
CREATE TABLE TB_PARCEIRO(
   ID_PARCEIRO     INTEGER  NOT NULL PRIMARY KEY 
  ,NOME_PARCEIRO   NVARCHAR(30) NOT NULL
  ,STATUS_PARCEIRO NVARCHAR(30) NOT NULL
  ,SEGMENTO        NVARCHAR(30) NOT NULL
);
INSERT INTO TB_PARCEIRO(ID_PARCEIRO,NOME_PARCEIRO,STATUS_PARCEIRO,SEGMENTO) VALUES (46,'Polishop','ATIVO','VARIEDADES');
INSERT INTO TB_PARCEIRO(ID_PARCEIRO,NOME_PARCEIRO,STATUS_PARCEIRO,SEGMENTO) VALUES (21271,'Natura','ATIVO','BELEZA');
INSERT INTO TB_PARCEIRO(ID_PARCEIRO,NOME_PARCEIRO,STATUS_PARCEIRO,SEGMENTO) VALUES (41431,'Spezziale','ATIVO','VARIEDADES');
INSERT INTO TB_PARCEIRO(ID_PARCEIRO,NOME_PARCEIRO,STATUS_PARCEIRO,SEGMENTO) VALUES (61783,'Diageo','ATIVO','BEBIDAS');
INSERT INTO TB_PARCEIRO(ID_PARCEIRO,NOME_PARCEIRO,STATUS_PARCEIRO,SEGMENTO) VALUES (61827,'Loja JBL','ATIVO','ELETRONICOS');
