use Teste_Analista_N2
CREATE TABLE TB_CAMPANHA(
   ID_CAMPANHA      INTEGER  NOT NULL PRIMARY KEY 
  ,NOME_CAMPANHA    NVARCHAR(30) NOT NULL
  ,FATOR_CONVERSAO  NUMERIC(30,10) NOT NULL
  ,STATUS           NVARCHAR(30) NOT NULL
  ,TIPO_FRETE       NVARCHAR(30) NOT NULL
  ,SEGMENTO_CLIENTE NVARCHAR(30) NOT NULL
); 
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (1,'Padrão','1','ATIVO','CLIENTE','VARIEDADES');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (10095,'Programa Nestle','1.03626943','INATIVO','CLIENTE','ALIMENTOS');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (40226,'Rede Natura','10','ATIVO','CAMPANHA','BELEZA');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (40362,'Clube LG 1 x 1','1','ATIVO','CLIENTE','ELETRONICOS');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (40367,'Cielo Fidelidade','232.5581395','INATIVO','CLIENTE','FINANCEIRO');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (40391,'Vivo B2B','0.200803213','ATIVO','CAMPANHA','TELEFONIA');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (40430,'Diageo Experience','1','INATIVO','CLIENTE','BEBIDAS');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (40515,'Meu Mundo Avon','142.8571429','ATIVO','CAMPANHA','BELEZA');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (40520,'Votorantin Somos Mais','232.5581395','ATIVO','CAMPANHA','CONSTRUÇÃO');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (50556,'Fast Shop Méliuz','1','INATIVO','CLIENTE','VARIEDADES');
INSERT INTO TB_CAMPANHA(ID_CAMPANHA,NOME_CAMPANHA,FATOR_CONVERSAO,STATUS,TIPO_FRETE,SEGMENTO_CLIENTE) VALUES (50578,'Suvinil Sou Mais','54.054054','ATIVO','CAMPANHA','CONSTRUÇÃO');
